// shortdict = 0.85% [0 - 304 bytes]
// advnames = 1.45% [304 - 517 bytes]
// advdesc = 23.14% [821 - 8260 bytes]
// msgs = 24.40% [9081 - 8710 bytes]
// msgs2 = 23.72% [17791 - 8467 bytes]
// verbs = 1.41% [26258 - 503 bytes]
// objs = 4.14% [26761 - 1478 bytes]
// objs_dir = 0.15% [28239 - 52 bytes]
// rooms = 1.01% [28291 - 361 bytes]
// packdata = 0.90% [28652 - 320 bytes]
// opcode_vrbidx_dir = 0.35% [28972 - 126 bytes]
// opcode_vrbidx_data = 2.11% [29098 - 752 bytes]
// opcode_pos = 1.26% [29850 - 450 bytes]
// opcode_len = 0.63% [30300 - 225 bytes]
// opcode_data = 11.98% [30525 - 4276 bytes]
// roomnameid = 0.09% [34801 - 33 bytes]
// roomdescid = 0.09% [34834 - 33 bytes]
// roomimg = 0.09% [34867 - 33 bytes]
// roomovrimg = 0.00% [34900 - 0 bytes]
// objnameid = 0.47% [34900 - 168 bytes]
// objdescid = 0.47% [35068 - 168 bytes]
// objimg = 0.00% [35236 - 0 bytes]
// objattr = 0.47% [35236 - 168 bytes]
// objloc = 0.47% [35404 - 168 bytes]
// objattrex = 0.00% [35572 - 0 bytes]
// roomstart = 0.00% [35572 - 1 bytes]
// roomattr = 0.09% [35573 - 33 bytes]
// roomattrex = 0.20% [35606 - 71 bytes]
// bitvars = 0.04% [35677 - 16 bytes]
// vars = -99.99% [35693 - -35693 bytes]
#define room_start 0
#define room_endgame 1
#define room_mainsquare 2
#define room_bankssquare 3
#define room_governorsquare 4
#define room_prison 5
#define room_cell 6
#define room_market 7
#define room_school 8
#define room_schoollibrary 9
#define room_schoolalley 10
#define room_northtownentrance 11
#define room_innhall 12
#define room_upcorridor 13
#define room_innroom 14
#define room_kitchen 15
#define room_southtownentrance 16
#define room_path 17
#define room_darkpath 18
#define room_betweenpath 19
#define room_mineroad 20
#define room_camp 21
#define room_redtent 22
#define room_house 23
#define room_houseinterior 24
#define room_ruins 25
#define room_ruinsinterior 26
#define room_forestpond 27
#define room_mountainpath 28
#define room_fall 29
#define room_mineentrance 30
#define room_minetunnel 31
#define room_forgeroom 32

#define obj_exits 0
#define obj_beerbarrel 1
#define obj_bow 2
#define obj_bread 3
#define obj_fish 4
#define obj_flask 5
#define obj_jacket 6
#define obj_knife 7
#define obj_rabbit 8
#define obj_stone 9
#define obj_twine 10
#define obj_yourself 11
#define obj_pendant 12
#define obj_roomkey 13
#define obj_pencil 14
#define obj_irillis 15
#define obj_rodum 16
#define obj_baryl 17
#define obj_map 18
#define obj_insignia 19
#define obj_eyes 20
#define obj_coin 21
#define obj_ring 22
#define obj_plate 23
#define obj_documents 24
#define obj_summoning 25
#define obj_lyrin 26
#define obj_witch 27
#define obj_sacred 28
#define obj_eriknotebook 29
#define obj_page 30
#define obj_nesterin 31
#define obj_erik 32
#define obj_eryan 33
#define obj_spell 34
#define obj_aki 35
#define obj_mainsquare_fountain 36
#define obj_mainsquare_benches 37
#define obj_mainsquare_people 38
#define obj_mainsquare_inn 39
#define obj_bankssquare_buildings 40
#define obj_bankssquare_statue 41
#define obj_bankssquare_instrument 42
#define obj_bankssquare_inscriptions 43
#define obj_bankssquare_layout 44
#define obj_governorsquare_prison 45
#define obj_governorsquare_guards 46
#define obj_governorsquare_coins 47
#define obj_governorsquare_fountain 48
#define obj_prison_door 49
#define obj_prison_desk 50
#define obj_prison_prisonguard 51
#define obj_prison_cell 52
#define obj_cell_woman 53
#define obj_market_building 54
#define obj_market_clothes 55
#define obj_market_clothessalesman 56
#define obj_market_food 57
#define obj_market_foodseller 58
#define obj_market_meat 59
#define obj_market_uniform 60
#define obj_market_school 61
#define obj_market_supplies 62
#define obj_market_rabbits 63
#define obj_school_cabinets 64
#define obj_school_stairs 65
#define obj_school_material 66
#define obj_schoollibrary_books 67
#define obj_schoollibrary_floor 68
#define obj_schoollibrary_history 69
#define obj_schoollibrary_geography 70
#define obj_schoollibrary_ancient 71
#define obj_schoollibrary_botany 72
#define obj_schoollibrary_berries 73
#define obj_schoollibrary_geometry 74
#define obj_schoollibrary_grimoire 75
#define obj_schoollibrary_banishing 76
#define obj_schoollibrary_arkylzoth 77
#define obj_schoolalley_door 78
#define obj_schoolalley_window 79
#define obj_schoolalley_school 80
#define obj_innhall_fireplace 81
#define obj_innhall_owner 82
#define obj_innhall_sign 83
#define obj_innhall_beer 84
#define obj_innhall_room 85
#define obj_innhall_kitchen 86
#define obj_innhall_tables 87
#define obj_upcorridor_doors 88
#define obj_upcorridor_rooms 89
#define obj_upcorridor_room 90
#define obj_innroom_bed 91
#define obj_innroom_furniture 92
#define obj_innroom_table 93
#define obj_innroom_drawer 94
#define obj_innroom_mattress 95
#define obj_kitchen_jars 96
#define obj_kitchen_windowdoor 97
#define obj_kitchen_cook 98
#define obj_kitchen_supplies 99
#define obj_kitchen_spices 100
#define obj_kitchen_help 101
#define obj_kitchen_school 102
#define obj_kitchen_kitchen 103
#define obj_kitchen_bench 104
#define obj_southtownentrance_entrance 105
#define obj_southtownentrance_forest 106
#define obj_southtownentrance_paths 107
#define obj_southtownentrance_road 108
#define obj_southtownentrance_leg 109
#define obj_southtownentrance_men 110
#define obj_southtownentrance_barrels 111
#define obj_southtownentrance_entranceguard 112
#define obj_southtownentrance_sign 113
#define obj_path_animals 114
#define obj_path_paths 115
#define obj_path_trees 116
#define obj_path_vegetation 117
#define obj_path_rabbits 118
#define obj_path_plants 119
#define obj_darkpath_branches 120
#define obj_darkpath_paths 121
#define obj_darkpath_trees 122
#define obj_betweenpath_paths 123
#define obj_mineroad_men 124
#define obj_mineroad_barrels 125
#define obj_mineroad_tarp 126
#define obj_mineroad_food 127
#define obj_mineroad_blankets 128
#define obj_mineroad_road 129
#define obj_camp_green 130
#define obj_camp_red 131
#define obj_house_door 132
#define obj_house_house 133
#define obj_house_walls 134
#define obj_house_grass 135
#define obj_houseinterior_bottle 136
#define obj_houseinterior_fireplace 137
#define obj_houseinterior_painting 138
#define obj_houseinterior_windows 139
#define obj_houseinterior_glass 140
#define obj_houseinterior_books 141
#define obj_ruins_slit 142
#define obj_ruins_door 143
#define obj_ruinsinterior_openings 144
#define obj_ruinsinterior_blood 145
#define obj_ruinsinterior_altar 146
#define obj_forestpond_plants 147
#define obj_forestpond_puddles 148
#define obj_forestpond_stream 149
#define obj_forestpond_watercourse 150
#define obj_mountainpath_mountains 151
#define obj_mountainpath_stones 152
#define obj_fall_creature 153
#define obj_fall_lake 154
#define obj_fall_mountains 155
#define obj_fall_path 156
#define obj_fall_waterfalls 157
#define obj_minetunnel_crossroads 158
#define obj_minetunnel_markings 159
#define obj_minetunnel_tunnels 160
#define obj_forgeroom_forge 161
#define obj_forgeroom_panel 162
#define obj_forgeroom_cross 163
#define obj_forgeroom_instrument 164
#define obj_forgeroom_triangle 165
#define obj_forgeroom_inscriptions 166
#define obj_forgeroom_drawings 167

#define vrb_onfirst 0
#define vrb_onenter 1
#define vrb_onleave 2
#define vrb_onturn 3
#define vrb_ondesc 4
#define vrb_u 5
#define vrb_d 6
#define vrb_s 7
#define vrb_n 8
#define vrb_w 9
#define vrb_e 10
#define vrb_se 11
#define vrb_sw 12
#define vrb_ne 13
#define vrb_nw 14
#define vrb_go 15
#define vrb_enter 16
#define vrb_x 17
#define vrb_take 18
#define vrb_drop 19
#define vrb_use 20
#define vrb_push 21
#define vrb_pull 22
#define vrb_open 23
#define vrb_close 24
#define vrb_lock 25
#define vrb_unlock 26
#define vrb_show 27
#define vrb_give 28
#define vrb_put 29
#define vrb_help 30
#define vrb_inventory 31
#define vrb_quit 32
#define vrb_restart 33
#define vrb_save 34
#define vrb_load 35
#define vrb_mem 36
#define vrb_gfx 37
#define vrb_talk 38
#define vrb_ask 39
#define vrb_drink 40
#define vrb_eat 41
#define vrb_fill 42
#define vrb_wear 43
#define vrb_takeoff 44
#define vrb_read 45
#define vrb_attack 46
#define vrb_capture 47
#define vrb_carve 48
#define vrb_cast 49
#define vrb_copy 50
#define vrb_cut 51
#define vrb_exit 52
#define vrb_hide 53
#define vrb_hunt 54
#define vrb_insert 55
#define vrb_kill 56
#define vrb_leave 57
#define vrb_move 58
#define vrb_search 59
#define vrb_throw 60

#define var_score 0
#define var_topscore 1
#define var_weight 2
#define var_maxweight 3
#define var_tmp 4

#define bitvar_irillisinbarrel 0
#define bitvar_roduminbarrel 1
#define bitvar_jacketon 2
#define bitvar_score_jacketwear 3
#define bitvar_insigniaonjacket 4
#define bitvar_baryleaten 5
#define bitvar_knowdarkpathroad 6
#define bitvar_score_knowdarkpathroad 7
#define bitvar_knowruinsroad 8
#define bitvar_score_knowruinsroad 9
#define bitvar_score_insigniaonjacket 10
#define bitvar_materialwin 11
#define bitvar_score_materialwin 12
#define bitvar_summoningstopped 13
#define bitvar_fulllayout 14
#define bitvar_layoutseen 15
#define bitvar_score_fulllayout 16
#define bitvar_solvedmaze 17
#define bitvar_score_solvedmaze 18
#define bitvar_knowdemonname 19
#define bitvar_pagetaken 20
#define bitvar_oldmandrank 21
#define bitvar_oldmaneat 22
#define bitvar_knowaboutcamp 23
#define bitvar_ringgiven 24
#define bitvar_manunderthebench 25
#define bitvar_discoveredman 26
#define bitvar_seeninstrument 27
#define bitvar_midday 28
#define bitvar_domidday 29
#define bitvar_score_coinstaken 30
#define bitvar_enteredprison 31
#define bitvar_score_prisonentered 32
#define bitvar_score_flaskfilled 33
#define bitvar_eryanname 34
#define bitvar_score_allowedtocell 35
#define bitvar_allowedtoenter 36
#define bitvar_womansawpendant 37
#define bitvar_alreadysaid 38
#define bitvar_score_geometrysection 39
#define bitvar_meatneeded 40
#define bitvar_rabbitsseen 41
#define bitvar_knowirillis 42
#define bitvar_rabbitgiven 43
#define bitvar_score_breadtaken 44
#define bitvar_wantjacket 45
#define bitvar_havemoney 46
#define bitvar_schoolseenfromnearby 47
#define bitvar_schoolalleyseen 48
#define bitvar_cabinetsbypassed 49
#define bitvar_twineseen 50
#define bitvar_score_twineseen 51
#define bitvar_cookhelps 52
#define bitvar_score_cabinetsbypassed 53
#define bitvar_pencilfound 54
#define bitvar_mapfound 55
#define bitvar_score_mapfound 56
#define bitvar_grimoireseen 57
#define bitvar_score_grimoireseen 58
#define bitvar_knowrodum 59
#define bitvar_knowbaryl 60
#define bitvar_knowberriesarebaryl 61
#define bitvar_score_berriesrecognized 62
#define bitvar_score_documentstaken 63
#define bitvar_score_spellseen 64
#define bitvar_pageshown 65
#define bitvar_score_spelltaken 66
#define bitvar_schoolpanelremoved 67
#define bitvar_score_schoolpanelremoved 68
#define bitvar_erikisdead 69
#define bitvar_signseen 70
#define bitvar_erikroom 71
#define bitvar_allowedinthekitchen 72
#define bitvar_ownersawpendant 73
#define bitvar_score_roomkey 74
#define bitvar_unlockedinnroom 75
#define bitvar_score_flask 76
#define bitvar_score_eriknotebook 77
#define bitvar_cookfillbarrel 78
#define bitvar_cookownsone 79
#define bitvar_cooksawpendant 80
#define bitvar_score_cookerik 81
#define bitvar_cookerik 82
#define bitvar_eryaninprison 83
#define bitvar_score_irilliswanted 84
#define bitvar_score_cookhelps 85
#define bitvar_barreldutyknow 86
#define bitvar_legseen 87
#define bitvar_barrelsseen 88
#define bitvar_score_barreldutyknow 89
#define bitvar_armedmenseen 90
#define bitvar_score_insigniataken 91
#define bitvar_score_rabbittaken 92
#define bitvar_bowneeded 93
#define bitvar_score_irillistaken 94
#define bitvar_score_rodumtaken 95
#define bitvar_bowmade 96
#define bitvar_score_bowmade 97
#define bitvar_menasleep 98
#define bitvar_barreltaken 99
#define bitvar_score_barreltaken 100
#define bitvar_mendead 101
#define bitvar_score_menasleep 102
#define bitvar_score_menasleeptried 103
#define bitvar_score_eryanname 104
#define bitvar_carvedeyes 105
#define bitvar_score_carvedeyes 106
#define bitvar_score_barylfound 107
#define bitvar_tasted 108
#define bitvar_score_tasted 109
#define bitvar_score_knowdemonname 110
#define bitvar_ruindooropened 111
#define bitvar_score_ruindooropened 112
#define bitvar_eyesonaltar 113
#define bitvar_bloodonaltar 114
#define bitvar_score_summoningstopped 115
#define bitvar_score_fishtaken 116
#define bitvar_defeatedfish 117
#define bitvar_score_defeatedfish 118
#define bitvar_forgeon 119
#define bitvar_gatesclosed 120
#define bitvar_forgeseen 121
#define bitvar_gatesseen 122
#define bitvar_score_gatesclosed 123

#define attr_visible 1
#define attr_actor 2
#define attr_listable 4
#define attr_takeable 8
#define attr_large 16
#define attr_openable 32
#define attr_open 64
#define attr_empty 128

