// shortdict = 0.86% [0 - 306 bytes]
// advnames = 1.47% [306 - 523 bytes]
// advdesc = 23.31% [829 - 8317 bytes]
// msgs = 24.35% [9146 - 8688 bytes]
// msgs2 = 23.92% [17834 - 8533 bytes]
// verbs = 1.41% [26367 - 503 bytes]
// objs = 4.16% [26870 - 1484 bytes]
// objs_dir = 0.15% [28354 - 52 bytes]
// rooms = 1.01% [28406 - 361 bytes]
// packdata = 0.90% [28767 - 320 bytes]
// opcode_vrbidx_dir = 0.35% [29087 - 126 bytes]
// opcode_vrbidx_data = 2.07% [29213 - 740 bytes]
// opcode_pos = 1.27% [29953 - 452 bytes]
// opcode_len = 0.63% [30405 - 226 bytes]
// opcode_data = 11.62% [30631 - 4147 bytes]
// roomnameid = 0.09% [34778 - 33 bytes]
// roomdescid = 0.09% [34811 - 33 bytes]
// roomimg = 0.09% [34844 - 33 bytes]
// roomovrimg = 0.00% [34877 - 0 bytes]
// objnameid = 0.48% [34877 - 170 bytes]
// objdescid = 0.48% [35047 - 170 bytes]
// objimg = 0.00% [35217 - 0 bytes]
// objattr = 0.48% [35217 - 170 bytes]
// objloc = 0.48% [35387 - 170 bytes]
// objattrex = 0.00% [35557 - 0 bytes]
// roomstart = 0.00% [35557 - 1 bytes]
// roomattr = 0.09% [35558 - 33 bytes]
// roomattrex = 0.20% [35591 - 71 bytes]
// bitvars = 0.03% [35662 - 10 bytes]
// vars = -99.99% [35672 - -35672 bytes]
#define room_start 0
#define room_endgame 1
#define room_mainsquare 2
#define room_bankssquare 3
#define room_governorsquare 4
#define room_prison 5
#define room_cell 6
#define room_market 7
#define room_school 8
#define room_schoollibrary 9
#define room_schoolalley 10
#define room_northtownentrance 11
#define room_innhall 12
#define room_upcorridor 13
#define room_innroom 14
#define room_kitchen 15
#define room_southtownentrance 16
#define room_path 17
#define room_darkpath 18
#define room_betweenpath 19
#define room_mineroad 20
#define room_camp 21
#define room_redtent 22
#define room_house 23
#define room_houseinterior 24
#define room_ruins 25
#define room_ruinsinterior 26
#define room_forestpond 27
#define room_mountainpath 28
#define room_fall 29
#define room_mineentrance 30
#define room_minetunnel 31
#define room_forgeroom 32

#define obj_exits 0
#define obj_beerbarrel 1
#define obj_bow 2
#define obj_bread 3
#define obj_fish 4
#define obj_flask 5
#define obj_jacket 6
#define obj_knife 7
#define obj_rabbit 8
#define obj_stone 9
#define obj_twine 10
#define obj_yourself 11
#define obj_pendant 12
#define obj_roomkey 13
#define obj_pencil 14
#define obj_irillis 15
#define obj_rodum 16
#define obj_baryl 17
#define obj_map 18
#define obj_insignia 19
#define obj_eyes 20
#define obj_coin 21
#define obj_ring 22
#define obj_plate 23
#define obj_documents 24
#define obj_summoning 25
#define obj_lyrin 26
#define obj_witch 27
#define obj_sacred 28
#define obj_eriknotebook 29
#define obj_page 30
#define obj_nesterin 31
#define obj_erik 32
#define obj_eryan 33
#define obj_spell 34
#define obj_aki 35
#define obj_mainsquare_fountain 36
#define obj_mainsquare_benches 37
#define obj_mainsquare_people 38
#define obj_mainsquare_inn 39
#define obj_bankssquare_buildings 40
#define obj_bankssquare_statue 41
#define obj_bankssquare_instrument 42
#define obj_bankssquare_inscriptions 43
#define obj_bankssquare_layout 44
#define obj_governorsquare_prison 45
#define obj_governorsquare_guards 46
#define obj_governorsquare_coins 47
#define obj_governorsquare_fountain 48
#define obj_prison_door 49
#define obj_prison_desk 50
#define obj_prison_prisonguard 51
#define obj_prison_cell 52
#define obj_cell_woman 53
#define obj_market_building 54
#define obj_market_clothes 55
#define obj_market_clothessalesman 56
#define obj_market_food 57
#define obj_market_foodseller 58
#define obj_market_meat 59
#define obj_market_uniform 60
#define obj_market_school 61
#define obj_market_suppliers 62
#define obj_market_rabbits 63
#define obj_school_cabinets 64
#define obj_school_stairs 65
#define obj_school_school 66
#define obj_school_material 67
#define obj_schoollibrary_books 68
#define obj_schoollibrary_floor 69
#define obj_schoollibrary_history 70
#define obj_schoollibrary_geography 71
#define obj_schoollibrary_ancient 72
#define obj_schoollibrary_botany 73
#define obj_schoollibrary_berries 74
#define obj_schoollibrary_geometry 75
#define obj_schoollibrary_grimoire 76
#define obj_schoollibrary_banishing 77
#define obj_schoollibrary_arkylzoth 78
#define obj_schoolalley_door 79
#define obj_schoolalley_window 80
#define obj_schoolalley_school 81
#define obj_innhall_fireplace 82
#define obj_innhall_owner 83
#define obj_innhall_sign 84
#define obj_innhall_inn 85
#define obj_innhall_beer 86
#define obj_innhall_room 87
#define obj_innhall_kitchen 88
#define obj_innhall_tables 89
#define obj_upcorridor_doors 90
#define obj_upcorridor_rooms 91
#define obj_upcorridor_room 92
#define obj_innroom_bed 93
#define obj_innroom_furniture 94
#define obj_innroom_table 95
#define obj_innroom_drawer 96
#define obj_innroom_mattress 97
#define obj_kitchen_jars 98
#define obj_kitchen_windowdoor 99
#define obj_kitchen_kitchen 100
#define obj_kitchen_cook 101
#define obj_kitchen_supplies 102
#define obj_kitchen_spices 103
#define obj_kitchen_help 104
#define obj_kitchen_school 105
#define obj_kitchen_bench 106
#define obj_southtownentrance_entrance 107
#define obj_southtownentrance_forest 108
#define obj_southtownentrance_paths 109
#define obj_southtownentrance_road 110
#define obj_southtownentrance_leg 111
#define obj_southtownentrance_men 112
#define obj_southtownentrance_barrels 113
#define obj_southtownentrance_entranceguard 114
#define obj_southtownentrance_sign 115
#define obj_path_animals 116
#define obj_path_paths 117
#define obj_path_trees 118
#define obj_path_vegetation 119
#define obj_path_rabbits 120
#define obj_path_plants 121
#define obj_darkpath_branches 122
#define obj_darkpath_paths 123
#define obj_darkpath_trees 124
#define obj_betweenpath_paths 125
#define obj_mineroad_men 126
#define obj_mineroad_barrels 127
#define obj_mineroad_tarp 128
#define obj_mineroad_food 129
#define obj_mineroad_blankets 130
#define obj_mineroad_road 131
#define obj_camp_green 132
#define obj_camp_red 133
#define obj_house_door 134
#define obj_house_house 135
#define obj_house_walls 136
#define obj_house_grass 137
#define obj_houseinterior_bottle 138
#define obj_houseinterior_fireplace 139
#define obj_houseinterior_painting 140
#define obj_houseinterior_windows 141
#define obj_houseinterior_glass 142
#define obj_houseinterior_books 143
#define obj_ruins_slit 144
#define obj_ruins_door 145
#define obj_ruinsinterior_openings 146
#define obj_ruinsinterior_blood 147
#define obj_ruinsinterior_altar 148
#define obj_forestpond_plants 149
#define obj_forestpond_puddles 150
#define obj_forestpond_stream 151
#define obj_forestpond_watercourse 152
#define obj_mountainpath_mountains 153
#define obj_mountainpath_stones 154
#define obj_fall_creature 155
#define obj_fall_lake 156
#define obj_fall_mountains 157
#define obj_fall_path 158
#define obj_fall_waterfalls 159
#define obj_minetunnel_crossroads 160
#define obj_minetunnel_markings 161
#define obj_minetunnel_tunnels 162
#define obj_forgeroom_forge 163
#define obj_forgeroom_panel 164
#define obj_forgeroom_cross 165
#define obj_forgeroom_instrument 166
#define obj_forgeroom_triangle 167
#define obj_forgeroom_inscriptions 168
#define obj_forgeroom_drawings 169

#define vrb_onfirst 0
#define vrb_onenter 1
#define vrb_onleave 2
#define vrb_onturn 3
#define vrb_ondesc 4
#define vrb_u 5
#define vrb_d 6
#define vrb_s 7
#define vrb_n 8
#define vrb_w 9
#define vrb_e 10
#define vrb_se 11
#define vrb_sw 12
#define vrb_ne 13
#define vrb_nw 14
#define vrb_go 15
#define vrb_enter 16
#define vrb_x 17
#define vrb_take 18
#define vrb_drop 19
#define vrb_use 20
#define vrb_push 21
#define vrb_pull 22
#define vrb_open 23
#define vrb_close 24
#define vrb_lock 25
#define vrb_unlock 26
#define vrb_show 27
#define vrb_give 28
#define vrb_put 29
#define vrb_help 30
#define vrb_inventory 31
#define vrb_quit 32
#define vrb_restart 33
#define vrb_save 34
#define vrb_load 35
#define vrb_mem 36
#define vrb_gfx 37
#define vrb_talk 38
#define vrb_ask 39
#define vrb_drink 40
#define vrb_eat 41
#define vrb_fill 42
#define vrb_wear 43
#define vrb_takeoff 44
#define vrb_read 45
#define vrb_attack 46
#define vrb_capture 47
#define vrb_carve 48
#define vrb_cast 49
#define vrb_copy 50
#define vrb_cut 51
#define vrb_exit 52
#define vrb_hide 53
#define vrb_hunt 54
#define vrb_insert 55
#define vrb_kill 56
#define vrb_leave 57
#define vrb_move 58
#define vrb_search 59
#define vrb_throw 60

#define var_score 0
#define var_topscore 1
#define var_weight 2
#define var_maxweight 3
#define var_tmp 4

#define bitvar_irillisinbarrel 0
#define bitvar_roduminbarrel 1
#define bitvar_jacketon 2
#define bitvar_insigniaonjacket 3
#define bitvar_baryleaten 4
#define bitvar_knowdarkpathroad 5
#define bitvar_knowruinsroad 6
#define bitvar_materialwin 7
#define bitvar_summoningstopped 8
#define bitvar_fulllayout 9
#define bitvar_layoutseen 10
#define bitvar_solvedmaze 11
#define bitvar_knowdemonname 12
#define bitvar_pagetaken 13
#define bitvar_oldmandrank 14
#define bitvar_oldmaneat 15
#define bitvar_knowaboutcamp 16
#define bitvar_ringgiven 17
#define bitvar_manunderthebench 18
#define bitvar_discoveredman 19
#define bitvar_seeninstrument 20
#define bitvar_midday 21
#define bitvar_domidday 22
#define bitvar_enteredprison 23
#define bitvar_eryanname 24
#define bitvar_allowedtoenter 25
#define bitvar_womansawpendant 26
#define bitvar_alreadysaid 27
#define bitvar_meatneeded 28
#define bitvar_rabbitsseen 29
#define bitvar_knowirillis 30
#define bitvar_rabbitgiven 31
#define bitvar_wantjacket 32
#define bitvar_havemoney 33
#define bitvar_schoolseenfromnearby 34
#define bitvar_schoolalleyseen 35
#define bitvar_cabinetsbypassed 36
#define bitvar_twineseen 37
#define bitvar_cookhelps 38
#define bitvar_pencilfound 39
#define bitvar_mapfound 40
#define bitvar_grimoireseen 41
#define bitvar_knowrodum 42
#define bitvar_knowbaryl 43
#define bitvar_knowberriesarebaryl 44
#define bitvar_schoolpanelremoved 45
#define bitvar_erikisdead 46
#define bitvar_signseen 47
#define bitvar_erikroom 48
#define bitvar_allowedinthekitchen 49
#define bitvar_ownersawpendant 50
#define bitvar_unlockedinnroom 51
#define bitvar_cookfillbarrel 52
#define bitvar_cookownsone 53
#define bitvar_cooksawpendant 54
#define bitvar_cookerik 55
#define bitvar_eryaninprison 56
#define bitvar_barreldutyknow 57
#define bitvar_legseen 58
#define bitvar_barrelsseen 59
#define bitvar_armedmenseen 60
#define bitvar_bowneeded 61
#define bitvar_menasleep 62
#define bitvar_barreltaken 63
#define bitvar_mendead 64
#define bitvar_carvedeyes 65
#define bitvar_tasted 66
#define bitvar_ruindooropened 67
#define bitvar_eyesonaltar 68
#define bitvar_bloodonaltar 69
#define bitvar_defeatedfish 70
#define bitvar_forgeon 71
#define bitvar_gatesclosed 72
#define bitvar_forgeseen 73
#define bitvar_gatesseen 74

#define attr_visible 1
#define attr_actor 2
#define attr_listable 4
#define attr_takeable 8
#define attr_large 16
#define attr_openable 32
#define attr_open 64
#define attr_empty 128

